version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      mi-red:
        ipv4_address: 10.0.1.2  # Asigna la dirección IP deseada para el servicio Node.js
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      mi-red:
        ipv4_address: 10.0.1.3  # Asigna la dirección IP deseada para el servicio MongoDB
    ports:
      - "27018:27017"

networks:
  mi-red:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24